// Entity Repositories (Interfaces)
export * from './IProjectRepository';
export * from './IWorkExperienceRepository';
export * from './IAcademicExperienceRepository';
export * from './IPersonalInfoRepository';
export * from './ICourseRepository';
export * from './ISkillRepository';
export * from './ISoftSkillRepository';

// Label Repositories (Interfaces)
export * from './labels/INavigationLabelsRepository';
export * from './labels/ICommonLabelsRepository';
export * from './labels/IWorkLabelsRepository';
export * from './labels/IEducationLabelsRepository';
export * from './labels/IAboutLabelsRepository';
export * from './labels/IFooterLabelsRepository';
export * from './labels/ISkillsLabelsRepository';
export * from './labels/ISoftSkillsLabelsRepository';
export * from './labels/IProjectLabelsRepository';
export * from './labels/ICourseLabelsRepository';
export * from './labels/IContactLabelsRepository';
